# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Office.delete_all
Office.create({"name":"Burlington, VT", "address":"64 Gricebrook Road Saint Albans, VT 05478"})
Office.create({"name":"Dallas, TX", "address":"6500 Campus Circle Drive East Irving, TX 75063"})
Office.create({"name":"Honolulu, HI", "address":"500 Ala Moana Boulevard Building 2, Room 400 Honolulu, Hawaii 96813"})
Office.create({"name":"Las Vegas, NV", "address":"5650 West Badura Avenue, Suite 100 Las Vegas, NV 89118"})
Office.create({"name":"Los Angeles, CA", "address":"300 North Los Angeles Street Los Angeles, CA 90012"})
Office.create({"name":"Miami, FL", "address":"8801 NW 7th Avenue Miami, FL 33150"})
Office.create({"name":"New Orleans, LA", "address":"1250 Poydras Street, Suite 1800, New Orleans, LA 70113"})
Office.create({"name":"San Francisco, CA", "address":"444 Washington Street San Francisco, CA 94111"})
Office.create({"name":"San Juan, PR", "address":"273 Ponce De Leon Ave., Suite 1100, San Juan, PR  00917"})
Office.create({"name":"St. Thomas, VI", "address":"8000 Nisky Center, Suite 1A Charlotte Amalie St. Thomas, USVI 00802"})
Office.create({"name":"Washington, DC", "address":"2675 Prosperity Avenue Fairfax, VA 22031-4906"})

Staff.delete_all
Staff.create({"login":"AlbertoTeeple","password":"password","office":"Burlington, VT","admin":1})
Staff.create({"login":"AllaNavarre","password":"password","office":"Dallas, TX","admin":1})
Staff.create({"login":"AndySolum","password":"password","office":"Honolulu, HI","admin":1})
Staff.create({"login":"AngelenaLindo","password":"password","office":"Las Vegas, NV","admin":1})
Staff.create({"login":"ArmandinaRoig","password":"password","office":"Los Angeles, CA","admin":1})
Staff.create({"login":"BethPeterson","password":"password","office":"Miami, FL","admin":1})
Staff.create({"login":"BobDenman","password":"password","office":"New Orleans, LA","admin":1})
Staff.create({"login":"BrittaneyMccarroll","password":"password","office":"San Francisco, CA","admin":1})
Staff.create({"login":"BrittaPieroni","password":"password","office":"San Juan, PR","admin":1})
Staff.create({"login":"CaitlynBrumbelow","password":"password","office":"St. Thomas, VI","admin":1})
Staff.create({"login":"CarterBohrer","password":"password","office":"Burlington, VT","admin":1})
Staff.create({"login":"DavidaHurwitz","password":"password","office":"Dallas, TX","admin":1})
Staff.create({"login":"DavidMacklin","password":"password","office":"Honolulu, HI","admin":1})
Staff.create({"login":"DonyaNelms","password":"password","office":"Las Vegas, NV","admin":1})
Staff.create({"login":"EnriquetaHenault","password":"password","office":"Los Angeles, CA","admin":1})
Staff.create({"login":"ErickaNobles","password":"password","office":"Miami, FL","admin":1})
Staff.create({"login":"FelixArend","password":"password","office":"New Orleans, LA","admin":1})
Staff.create({"login":"FerdinandRosenfield","password":"password","office":"San Francisco, CA","admin":1})
Staff.create({"login":"GinaHarley","password":"password","office":"San Juan, PR","admin":1})
Staff.create({"login":"HerminaDisandro","password":"password","office":"St. Thomas, VI","admin":1})
Staff.create({"login":"HollisBad","password":"password","office":"Burlington, VT","admin":0})
Staff.create({"login":"IrwinLamey","password":"password","office":"Dallas, TX","admin":0})
Staff.create({"login":"JacquelinHollander","password":"password","office":"Honolulu, HI","admin":0})
Staff.create({"login":"JordanMccampbell","password":"password","office":"Las Vegas, NV","admin":0})
Staff.create({"login":"JosphineDisanto","password":"password","office":"Los Angeles, CA","admin":0})
Staff.create({"login":"JoyCaulkins","password":"password","office":"Miami, FL","admin":0})
Staff.create({"login":"KandisNowakowski","password":"password","office":"New Orleans, LA","admin":0})
Staff.create({"login":"KelleyMayo","password":"password","office":"San Francisco, CA","admin":0})
Staff.create({"login":"KelsieSagers","password":"password","office":"San Juan, PR","admin":0})
Staff.create({"login":"KentonOliver","password":"password","office":"St. Thomas, VI","admin":0})
Staff.create({"login":"KenyaSamuel","password":"password","office":"Washington, DC","admin":0})
Staff.create({"login":"LeanSauer","password":"password","office":"Burlington, VT","admin":0})
Staff.create({"login":"LoisKauffman","password":"password","office":"Dallas, TX","admin":0})
Staff.create({"login":"LoveGorton","password":"password","office":"Honolulu, HI","admin":0})
Staff.create({"login":"LuveniaJacob","password":"password","office":"Las Vegas, NV","admin":0})
Staff.create({"login":"LynwoodLeday","password":"password","office":"Los Angeles, CA","admin":0})
Staff.create({"login":"MarlenKollman","password":"password","office":"Miami, FL","admin":0})
Staff.create({"login":"MarshallWoodside","password":"password","office":"New Orleans, LA","admin":0})
Staff.create({"login":"MiquelQuesnel","password":"password","office":"San Francisco, CA","admin":0})
Staff.create({"login":"MitchellParisi","password":"password","office":"San Juan, PR","admin":0})
Staff.create({"login":"MitsukoIsakson","password":"password","office":"St. Thomas, VI","admin":0})
Staff.create({"login":"MorrisEchols","password":"password","office":"Washington, DC","admin":0})
Staff.create({"login":"MorrisKing","password":"password","office":"Burlington, VT","admin":0})
Staff.create({"login":"MosheBowser","password":"password","office":"Dallas, TX","admin":0})
Staff.create({"login":"NathalieDraves","password":"password","office":"Honolulu, HI","admin":0})
Staff.create({"login":"NetaMirsky","password":"password","office":"Las Vegas, NV","admin":0})
Staff.create({"login":"NikoleMisiewicz","password":"password","office":"Los Angeles, CA","admin":0})
Staff.create({"login":"NorineBradshaw","password":"password","office":"Miami, FL","admin":0})
Staff.create({"login":"OlgaJohnston","password":"password","office":"New Orleans, LA","admin":0})
Staff.create({"login":"PearleneGauger","password":"password","office":"San Francisco, CA","admin":0})
Staff.create({"login":"PearlieKeene","password":"password","office":"San Juan, PR","admin":0})
Staff.create({"login":"PenniReimann","password":"password","office":"St. Thomas, VI","admin":0})
Staff.create({"login":"RachelValliere","password":"password","office":"Washington, DC","admin":0})
Staff.create({"login":"RichardConti","password":"password","office":"Burlington, VT","admin":0})
Staff.create({"login":"RickyHeyward","password":"password","office":"Dallas, TX","admin":0})


Staff.create({"login":"RobertCook","password":"password","office":"Honolulu, HI","admin":0})
Staff.create({"login":"RochellAttaway","password":"password","office":"Las Vegas, NV","admin":0})
Staff.create({"login":"RuthDominguez","password":"password","office":"Los Angeles, CA","admin":0})
Staff.create({"login":"RutheMatta","password":"password","office":"Miami, FL","admin":0})
Staff.create({"login":"SalBalderas","password":"password","office":"New Orleans, LA","admin":0})
Staff.create({"login":"ShaniBankes","password":"password","office":"San Francisco, CA","admin":0})
Staff.create({"login":"SharriByrnes","password":"password","office":"San Juan, PR","admin":0})
Staff.create({"login":"ShinDorner","password":"password","office":"St. Thomas, VI","admin":0})
Staff.create({"login":"ThuLupo","password":"password","office":"Washington, DC","admin":0})
Staff.create({"login":"TwylaKamerer","password":"password","office":"Burlington, VT","admin":0})
Staff.create({"login":"ValentineDitmore","password":"password","office":"Dallas, TX","admin":0})
Staff.create({"login":"WinniePearcy","password":"password","office":"Honolulu, HI","admin":0})
Staff.create({"login":"SarahFahden","password":"password","office":"Washington, DC","admin":0})
Staff.create({"login":"LenShmunis","password":"password","office":"Washington, DC","admin":1})
Staff.create({"login":"EricJeanmaire","password":"password","office":"Dallas, TX","admin":1})
Staff.create({"login":"TommyKim","password":"password","office":"Washington, DC","admin":1})
